<?php
 return array (
  'cid' => '1',
  'siteid' => '1',
  'keyid' => 'content',
  'name' => '普通住宅',
  'mb' => '',
  'catdir' => 'putongzhuzhai',
  'parentdir' => 'putongzhuzhai',
  'pid' => '0',
  'type' => '0',
  'child' => '0',
  'modelid' => '1000',
  'sort' => '0',
  'domain' => '',
  'url' => '/index.php?v=listing&cid=1&page=1',
  'thumb' => '',
  'icon' => '',
  'workflowid' => '0',
  'showloop' => '1',
  'ismenu' => '1',
  'mshow' => '1',
  'listhtml' => '0',
  'showhtml' => '0',
  'listurl' => 'index.php?v=listing&cid={$cid}&page={$page}',
  'showurl' => 'index.php?v=show&cid={$cid}&id={$id}',
  'category_template' => '',
  'list_template' => '',
  'show_template' => '',
  'seo_title' => '北京装修公司大全_北京专业装修公司_北京装修公司推荐排名 – 优装美家装修网',
  'seo_keywords' => '',
  'seo_description' => '',
  'ishot' => '0',
)?>