<?php
 return array (
  'cid' => '187',
  'siteid' => '1',
  'keyid' => 'content',
  'name' => '品牌汇显示列表',
  'mb' => '',
  'catdir' => 'pinpaihuixianshiliebiao',
  'parentdir' => 'pinpaihuixianshiliebiao',
  'pid' => '0',
  'type' => '0',
  'child' => '0',
  'modelid' => '1009',
  'sort' => '0',
  'domain' => '',
  'url' => '/index.php?v=listing&cid=187&page=1',
  'thumb' => '',
  'icon' => '',
  'workflowid' => '0',
  'showloop' => '1',
  'ismenu' => '1',
  'mshow' => '1',
  'listhtml' => '0',
  'showhtml' => '0',
  'listurl' => 'index.php?v=listing&cid={$cid}&page={$page}',
  'showurl' => 'index.php?v=show&cid={$cid}&id={$id}',
  'category_template' => '',
  'list_template' => 'uzhuang:brands_list',
  'show_template' => '',
  'seo_title' => '[优装美家品牌惠]家装建材海量精选 品牌信赖 一站购买',
  'seo_keywords' => '家居,建材市场,家居网,家居商城,家具,装饰,装修,建材,网上商城',
  'seo_description' => '优装美家品牌惠，是国内最大的家具、家居、建材、装饰,装修为一体的网上装修商城。优装美家家居网，全国最大最专业的网上家居装修商城。',
  'ishot' => '0',
)?>