<?php
 return array (
  1 => 
  array (
    'name' => '普通住宅',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'putongzhuzhai',
    'url' => '/index.php?v=listing&cid=1&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  2 => 
  array (
    'name' => '小户型',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'xiaohuxing',
    'url' => '/index.php?v=listing&cid=2&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  3 => 
  array (
    'name' => '别墅',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'bieshu',
    'url' => '/index.php?v=listing&cid=3&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  4 => 
  array (
    'name' => '局部装修',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'jubuzhuangxiu',
    'url' => '/index.php?v=listing&cid=4&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  5 => 
  array (
    'name' => '商铺',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'shangpu',
    'url' => '/index.php?v=listing&cid=5&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  6 => 
  array (
    'name' => 'ktv',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'ktv',
    'url' => '/index.php?v=listing&cid=6&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  7 => 
  array (
    'name' => '餐厅/酒楼',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'cantingjiulou',
    'url' => '/index.php?v=listing&cid=7&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  8 => 
  array (
    'name' => '美容/美发',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'meirongmeifa',
    'url' => '/index.php?v=listing&cid=8&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  9 => 
  array (
    'name' => '娱乐场所',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'yulechangsuo',
    'url' => '/index.php?v=listing&cid=9&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  10 => 
  array (
    'name' => '展厅',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'zhanting',
    'url' => '/index.php?v=listing&cid=10&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  11 => 
  array (
    'name' => '办公室',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1000',
    'catdir' => 'bangongshi',
    'url' => '/index.php?v=listing&cid=11&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  12 => 
  array (
    'name' => '装修课堂',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'ketang',
    'url' => '/zhuangxiuketang/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '1',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  13 => 
  array (
    'name' => '装修管家',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'guanjia',
    'url' => '/zhuangxiuguanjia/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '1',
    'listhtml' => '1',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  14 => 
  array (
    'name' => '环保服务',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'huanbao',
    'url' => '/index.php?v=listing&cid=14&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  26 => 
  array (
    'name' => '家装选材',
    'pid' => '12',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'xuancaiketang',
    'url' => '/zhuangxiuketang/26-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  27 => 
  array (
    'name' => '装修知识',
    'pid' => '12',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'zhuanjiaketang',
    'url' => '/zhuangxiuketang/27-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  30 => 
  array (
    'name' => '家居风水与保养',
    'pid' => '12',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'jiajuzixun',
    'url' => '/zhuangxiuketang/30-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  31 => 
  array (
    'name' => '装修风格与技巧',
    'pid' => '12',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'jiajuredianzhuanti',
    'url' => '/zhuangxiuketang/31-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  32 => 
  array (
    'name' => '建材',
    'pid' => '26',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'jiancai',
    'url' => '/zhuangxiuketang/32-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  33 => 
  array (
    'name' => '家具',
    'pid' => '26',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'jiaju',
    'url' => '/zhuangxiuketang/33-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  34 => 
  array (
    'name' => '软装',
    'pid' => '26',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'ruanzhuang',
    'url' => '/zhuangxiuketang/34-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  35 => 
  array (
    'name' => '电器',
    'pid' => '26',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'dianqi',
    'url' => '/zhuangxiuketang/35-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  36 => 
  array (
    'name' => '灯具',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'dengju',
    'url' => '/zhuangxiuketang/36-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  37 => 
  array (
    'name' => '卫浴设备',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'weiyushebei',
    'url' => '/zhuangxiuketang/37-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  38 => 
  array (
    'name' => '油漆',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'youqi',
    'url' => '/zhuangxiuketang/38-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  39 => 
  array (
    'name' => '瓷砖',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'cizhuan',
    'url' => '/zhuangxiuketang/39-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  40 => 
  array (
    'name' => '门窗',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'menchuang',
    'url' => '/zhuangxiuketang/40-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  41 => 
  array (
    'name' => '五金',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'wujin',
    'url' => '/zhuangxiuketang/41-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  42 => 
  array (
    'name' => '橱柜',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'chugui',
    'url' => '/zhuangxiuketang/42-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  43 => 
  array (
    'name' => '地板',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'deban',
    'url' => '/zhuangxiuketang/43-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  44 => 
  array (
    'name' => '暖气设备',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'nuanqishebei',
    'url' => '/zhuangxiuketang/44-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  45 => 
  array (
    'name' => '壁纸',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'bizhi',
    'url' => '/zhuangxiuketang/45-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  46 => 
  array (
    'name' => '水龙头',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'shuilongtou',
    'url' => '/zhuangxiuketang/46-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  47 => 
  array (
    'name' => '天花板/吊顶',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'tianhuabandiaoding',
    'url' => '/zhuangxiuketang/47-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  48 => 
  array (
    'name' => '建筑构件',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'jianzhugoujian',
    'url' => '/zhuangxiuketang/48-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  49 => 
  array (
    'name' => '装修材料',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'zhuangxiucailiao',
    'url' => '/zhuangxiuketang/49-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  50 => 
  array (
    'name' => '厨房用具',
    'pid' => '32',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'chufangyongju',
    'url' => '/zhuangxiuketang/50-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  51 => 
  array (
    'name' => '家具',
    'pid' => '33',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'jiaju',
    'url' => '/zhuangxiuketang/51-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  52 => 
  array (
    'name' => '儿童家具',
    'pid' => '33',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'ertongjiaju',
    'url' => '/zhuangxiuketang/52-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  53 => 
  array (
    'name' => '地毯',
    'pid' => '34',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'detan',
    'url' => '/zhuangxiuketang/53-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  54 => 
  array (
    'name' => '窗帘',
    'pid' => '34',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'chuanglian',
    'url' => '/zhuangxiuketang/54-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  55 => 
  array (
    'name' => '日用杂品',
    'pid' => '34',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'riyongzapin',
    'url' => '/zhuangxiuketang/55-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  56 => 
  array (
    'name' => '饰品',
    'pid' => '34',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'shipin',
    'url' => '/zhuangxiuketang/56-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  57 => 
  array (
    'name' => '办公设备',
    'pid' => '35',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'bangongshebei',
    'url' => '/zhuangxiuketang/57-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  58 => 
  array (
    'name' => '家用电器',
    'pid' => '35',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'jiayongdianqi',
    'url' => '/zhuangxiuketang/58-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  59 => 
  array (
    'name' => '厨用电器',
    'pid' => '35',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'chuyongdianqi',
    'url' => '/zhuangxiuketang/59-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  60 => 
  array (
    'name' => '装修基础指南',
    'pid' => '27',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'zhuangxiujichuzhinan',
    'url' => '/zhuangxiuketang/60-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  61 => 
  array (
    'name' => '装修前',
    'pid' => '27',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'zhuangxiuqian',
    'url' => '/zhuangxiuketang/61-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  62 => 
  array (
    'name' => '装修中',
    'pid' => '27',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'zhuangxiuzhong',
    'url' => '/zhuangxiuketang/62-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  63 => 
  array (
    'name' => '装修后',
    'pid' => '27',
    'child' => '1',
    'modelid' => '1004',
    'catdir' => 'zhuangxiuhou',
    'url' => '/zhuangxiuketang/63-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  64 => 
  array (
    'name' => '基础知识',
    'pid' => '60',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'zhuangxiuzhishi',
    'url' => '/zhuangxiuketang/64-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  65 => 
  array (
    'name' => '装修入门',
    'pid' => '60',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'zhuangxiurumen',
    'url' => '/zhuangxiuketang/65-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  66 => 
  array (
    'name' => '收房',
    'pid' => '61',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'shoufang',
    'url' => '/zhuangxiuketang/66-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  67 => 
  array (
    'name' => '设计',
    'pid' => '61',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'sheji',
    'url' => '/zhuangxiuketang/67-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  68 => 
  array (
    'name' => '预算',
    'pid' => '61',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'yusuan',
    'url' => '/zhuangxiuketang/68-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  69 => 
  array (
    'name' => '合同',
    'pid' => '61',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'hetong',
    'url' => '/zhuangxiuketang/69-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  70 => 
  array (
    'name' => '拆改',
    'pid' => '62',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'chaigai',
    'url' => '/zhuangxiuketang/70-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  71 => 
  array (
    'name' => '水电',
    'pid' => '62',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'shuidian',
    'url' => '/zhuangxiuketang/71-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  72 => 
  array (
    'name' => '防水',
    'pid' => '62',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'fangshui',
    'url' => '/zhuangxiuketang/72-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  73 => 
  array (
    'name' => '泥瓦',
    'pid' => '62',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'niwa',
    'url' => '/zhuangxiuketang/73-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  74 => 
  array (
    'name' => '木工',
    'pid' => '62',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'mugong',
    'url' => '/zhuangxiuketang/74-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  75 => 
  array (
    'name' => '油漆',
    'pid' => '62',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'youqi',
    'url' => '/zhuangxiuketang/75-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  76 => 
  array (
    'name' => '竣工',
    'pid' => '62',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'jungong',
    'url' => '/zhuangxiuketang/76-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  81 => 
  array (
    'name' => '软装',
    'pid' => '63',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'ruanzhuang',
    'url' => '/zhuangxiuketang/81-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  82 => 
  array (
    'name' => '环保',
    'pid' => '63',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'huanbao',
    'url' => '/zhuangxiuketang/82-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  83 => 
  array (
    'name' => '入住',
    'pid' => '63',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'ruzhu',
    'url' => '/zhuangxiuketang/83-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  85 => 
  array (
    'name' => '建材商场活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'jiancaishangchanghuodong',
    'url' => '/zhuangxiuketang/85-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  87 => 
  array (
    'name' => '家居风水',
    'pid' => '30',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'jiajufengshui',
    'url' => '/zhuangxiuketang/87-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  88 => 
  array (
    'name' => '行业动态',
    'pid' => '30',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'xingyedongtai',
    'url' => '/zhuangxiuketang/88-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  89 => 
  array (
    'name' => '资讯排行榜',
    'pid' => '30',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'zixunpaixingbang',
    'url' => '/zhuangxiuketang/89-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  90 => 
  array (
    'name' => '装修技巧',
    'pid' => '31',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'zhuangxiujiqiao',
    'url' => '/zhuangxiuketang/90-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  91 => 
  array (
    'name' => '风格专题',
    'pid' => '31',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'fenggezhuanti',
    'url' => '/zhuangxiuketang/91-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  92 => 
  array (
    'name' => '环保专题',
    'pid' => '31',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'huanbaozhuanti',
    'url' => '/zhuangxiuketang/92-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  93 => 
  array (
    'name' => '装饰搭配',
    'pid' => '31',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'zhuangshidapei',
    'url' => '/zhuangxiuketang/93-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  98 => 
  array (
    'name' => '卖家入驻',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'maijiaruzhu',
    'url' => '/index.php?v=listing&cid=98&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  99 => 
  array (
    'name' => '店铺续约/关店',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'dianpuxuyueguandian',
    'url' => '/index.php?v=listing&cid=99&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  100 => 
  array (
    'name' => '店铺管理',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'dianpuguanli',
    'url' => '/index.php?v=listing&cid=100&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  101 => 
  array (
    'name' => '退款/售后',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'tuikuanshouhou',
    'url' => '/index.php?v=listing&cid=101&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  102 => 
  array (
    'name' => '卖家服务支持',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'maijiafuwuzhichi',
    'url' => '/index.php?v=listing&cid=102&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  130 => 
  array (
    'name' => '公司相关',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'gongsixiangguan',
    'url' => '/index.php?v=listing&cid=130&page=1',
    'showloop' => '1',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  131 => 
  array (
    'name' => '关于我们',
    'pid' => '130',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'guanyuwomen',
    'url' => '/index.php?v=listing&cid=131&page=1',
    'showloop' => '1',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  132 => 
  array (
    'name' => '吉祥物介绍',
    'pid' => '130',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'lianxiwomen',
    'url' => '/index.php?v=listing&cid=132&page=1',
    'showloop' => '1',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  133 => 
  array (
    'name' => '法律声明',
    'pid' => '130',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'falvshengming',
    'url' => '/index.php?v=listing&cid=133&page=1',
    'showloop' => '1',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  134 => 
  array (
    'name' => '设计团队',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1003',
    'catdir' => 'shejituandui',
    'url' => '/index.php?v=listing&cid=134&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  135 => 
  array (
    'name' => '发标',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1002',
    'catdir' => 'fabiao',
    'url' => '/index.php?v=listing&cid=135&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  136 => 
  array (
    'name' => '图库',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1001',
    'catdir' => 'tuku',
    'url' => '/index.php?v=listing&cid=136&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  137 => 
  array (
    'name' => '优惠活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1005',
    'catdir' => 'youhuihuodong',
    'url' => '/index.php?v=listing&cid=137&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  138 => 
  array (
    'name' => '装修保险',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1006',
    'catdir' => 'zhuangxiubaoxian',
    'url' => '/index.php?v=listing&cid=138&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  141 => 
  array (
    'name' => '配送咨询',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'peisongzixun',
    'url' => '/index.php?v=listing&cid=141&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  142 => 
  array (
    'name' => '付款及退款',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'fukuanjituikuan',
    'url' => '/index.php?v=listing&cid=142&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  143 => 
  array (
    'name' => '售后规则',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shouhouguize',
    'url' => '/index.php?v=listing&cid=143&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  144 => 
  array (
    'name' => '装修设计',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhuangxiusheji',
    'url' => '/index.php?v=listing&cid=144&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  145 => 
  array (
    'name' => '管家服务',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'guanjiafuwu',
    'url' => '/index.php?v=listing&cid=145&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  146 => 
  array (
    'name' => '装修保险',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhuangxiubaoxian',
    'url' => '/index.php?v=listing&cid=146&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  147 => 
  array (
    'name' => '帮助中心',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'bangzhuzhongxin',
    'url' => '/index.php?v=listing&cid=147&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  148 => 
  array (
    'name' => '买家帮助中心',
    'pid' => '147',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'maijiabangzhuzhongxin',
    'url' => '/index.php?v=listing&cid=148&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  149 => 
  array (
    'name' => '商家帮助中心',
    'pid' => '147',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'shangjiabangzhuzhongxin',
    'url' => '/index.php?v=listing&cid=149&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  151 => 
  array (
    'name' => '热点问题',
    'pid' => '147',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'redianwenti',
    'url' => '/index.php?v=listing&cid=151&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  152 => 
  array (
    'name' => '规则体系',
    'pid' => '149',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'guizetixi',
    'url' => '/index.php?v=listing&cid=152&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  153 => 
  array (
    'name' => '卖家入驻',
    'pid' => '149',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'maijiaruzhu',
    'url' => '/index.php?v=listing&cid=153&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  154 => 
  array (
    'name' => '店铺续约/关店',
    'pid' => '149',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'dianpuxuyueguandian',
    'url' => '/index.php?v=listing&cid=154&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  155 => 
  array (
    'name' => '店铺管理',
    'pid' => '149',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'dianpuguanli',
    'url' => '/index.php?v=listing&cid=155&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  156 => 
  array (
    'name' => '退款/售后',
    'pid' => '149',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'tuikuanshouhou',
    'url' => '/index.php?v=listing&cid=156&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  157 => 
  array (
    'name' => '卖家服务支持',
    'pid' => '149',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'maijiafuwuzhichi',
    'url' => '/index.php?v=listing&cid=157&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  158 => 
  array (
    'name' => '物流配送',
    'pid' => '148',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'wuliupeisong',
    'url' => '/index.php?v=listing&cid=158&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  159 => 
  array (
    'name' => '交易管理',
    'pid' => '148',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiaoyiguanli',
    'url' => '/index.php?v=listing&cid=159&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  160 => 
  array (
    'name' => '支付管理',
    'pid' => '148',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhifuguanli',
    'url' => '/index.php?v=listing&cid=160&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  161 => 
  array (
    'name' => '账户管理',
    'pid' => '148',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhanghuguanli',
    'url' => '/index.php?v=listing&cid=161&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  162 => 
  array (
    'name' => '购买咨询',
    'pid' => '151',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'goumaizixun',
    'url' => '/index.php?v=listing&cid=162&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  163 => 
  array (
    'name' => '配送咨询',
    'pid' => '151',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'peisongzixun',
    'url' => '/index.php?v=listing&cid=163&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  164 => 
  array (
    'name' => '付款及退款',
    'pid' => '151',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'fukuanjituikuan',
    'url' => '/index.php?v=listing&cid=164&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  165 => 
  array (
    'name' => '售后规则',
    'pid' => '151',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shouhouguize',
    'url' => '/index.php?v=listing&cid=165&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  166 => 
  array (
    'name' => '装修设计',
    'pid' => '151',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhuangxiusheji',
    'url' => '/index.php?v=listing&cid=166&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  167 => 
  array (
    'name' => '管家服务',
    'pid' => '151',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'guanjiafuwu',
    'url' => '/index.php?v=listing&cid=167&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  168 => 
  array (
    'name' => '装修保险',
    'pid' => '151',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhuangxiubaoxian',
    'url' => '/index.php?v=listing&cid=168&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  169 => 
  array (
    'name' => '新手指南',
    'pid' => '147',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'xinshouzhinan',
    'url' => '/index.php?v=listing&cid=169&page=1',
    'showloop' => '0',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  170 => 
  array (
    'name' => '家居保养',
    'pid' => '30',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'jiajubaoyang',
    'url' => '/zhuangxiuketang/170-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  171 => 
  array (
    'name' => '床上用品',
    'pid' => '34',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'chuangshangyongpin',
    'url' => '/zhuangxiuketang/171-1/',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  172 => 
  array (
    'name' => '品牌惠列表',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'pinpaihui',
    'url' => '/index.php?v=listing&cid=172&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  174 => 
  array (
    'name' => '加入我们',
    'pid' => '130',
    'child' => '0',
    'modelid' => '1007',
    'catdir' => 'jiaruwomen',
    'url' => '/index.php?v=listing&cid=174&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  177 => 
  array (
    'name' => '法律声明',
    'pid' => '130',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'falvshengming',
    'url' => '/index.php?v=listing&cid=177&page=1',
    'showloop' => '1',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  178 => 
  array (
    'name' => '服务协议',
    'pid' => '130',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'fuwuxieyi',
    'url' => '/index.php?v=listing&cid=178&page=1',
    'showloop' => '1',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  179 => 
  array (
    'name' => 'Ʒ',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'pinpaihui',
    'url' => '/index.php?v=listing&cid=179',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  180 => 
  array (
    'name' => '首页大图',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shouyedatu',
    'url' => '/index.php?v=listing&cid=180&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  181 => 
  array (
    'name' => '建材家居',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiancaijiaju',
    'url' => '/index.php?v=listing&cid=181&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  182 => 
  array (
    'name' => '我要装修全站弹窗',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'woyaozhuangxiuquanzhantanchuan',
    'url' => '/index.php?v=listing&cid=182&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  183 => 
  array (
    'name' => '团队介绍',
    'pid' => '130',
    'child' => '0',
    'modelid' => '1008',
    'catdir' => 'tuanduijieshao',
    'url' => '/index.php?v=listing&cid=183&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  184 => 
  array (
    'name' => '专题单页',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhuantidanye',
    'url' => '/index.php?v=listing&cid=184&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  185 => 
  array (
    'name' => '联系我们',
    'pid' => '130',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'lianxiwomen',
    'url' => '/index.php?v=listing&cid=185&page=1',
    'showloop' => '1',
    'type' => '1',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  187 => 
  array (
    'name' => '品牌汇显示列表',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1009',
    'catdir' => 'pinpaihuixianshiliebiao',
    'url' => '/index.php?v=listing&cid=187&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  188 => 
  array (
    'name' => '品牌汇大图',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'pinpaihuidatu',
    'url' => '/index.php?v=listing&cid=188&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  193 => 
  array (
    'name' => '中奖名单',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhongjiangmingidan',
    'url' => '/index.php?v=listing&cid=193&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  195 => 
  array (
    'name' => '装小白',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhuangxiaobai',
    'url' => '/index.php?v=listing&cid=195&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  196 => 
  array (
    'name' => '装修包',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhuangxiubao',
    'url' => '/index.php?v=listing&cid=196&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  197 => 
  array (
    'name' => '首页顶通广告',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'dingtong',
    'url' => '/index.php?v=listing&cid=197&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  198 => 
  array (
    'name' => '装修管家22条准则',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zxgj_catch22',
    'url' => '/index.php?v=listing&cid=198&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  199 => 
  array (
    'name' => '生活家嗨爆11',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shj-high11',
    'url' => '/index.php?v=listing&cid=199&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  200 => 
  array (
    'name' => '九折装修',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiuzhezhuangxiu',
    'url' => '/index.php?v=listing&cid=200&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  201 => 
  array (
    'name' => '品宣视频聚合页',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'pxspjhy',
    'url' => '/index.php?v=listing&cid=201&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  202 => 
  array (
    'name' => '轻舟666',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'qingzhou666',
    'url' => '/index.php?v=listing&cid=202&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  203 => 
  array (
    'name' => '登录页广告',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'dengluyeguanggao',
    'url' => '/index.php?v=listing&cid=203&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  204 => 
  array (
    'name' => '广州首页大图',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'guangzhoushouyedatu',
    'url' => '/index.php?v=listing&cid=204&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '326',
    'icon' => '',
  ),
  205 => 
  array (
    'name' => '深圳首页大图',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shenzhenshouyedatu',
    'url' => '/index.php?v=listing&cid=205&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '328',
    'icon' => '',
  ),
  206 => 
  array (
    'name' => '天津首页大图',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'tianjinshouyedatu',
    'url' => '/index.php?v=listing&cid=206&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '3362',
    'icon' => '',
  ),
  207 => 
  array (
    'name' => '开工证',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'kaigongzheng',
    'url' => '/index.php?v=listing&cid=207&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  219 => 
  array (
    'name' => '精品案例',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1031',
    'catdir' => 'jingpinanli',
    'url' => '/index.php?v=listing&cid=219&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '0',
    'icon' => '',
  ),
  220 => 
  array (
    'name' => '公司',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1032',
    'catdir' => 'gongsi',
    'url' => '/index.php?v=listing&cid=220&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '0',
    'icon' => '',
  ),
  221 => 
  array (
    'name' => '设计师',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1033',
    'catdir' => 'shejishi',
    'url' => '/index.php?v=listing&cid=221&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '0',
    'icon' => '',
  ),
  222 => 
  array (
    'name' => '轮播图移动站',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1034',
    'catdir' => 'lunbotuyidongzhan',
    'url' => '/index.php?v=listing&cid=222&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '0',
    'icon' => '',
  ),
  223 => 
  array (
    'name' => '专题图移动站',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1035',
    'catdir' => 'zhuantituyidongzhan',
    'url' => '/index.php?v=listing&cid=223&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '0',
    'icon' => '',
  ),
  224 => 
  array (
    'name' => '上海首页大图',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shanghaishouyedatu',
    'url' => '/index.php?v=listing&cid=224&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '3361',
    'icon' => '',
  ),
  225 => 
  array (
    'name' => '西安首页大图',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'xianshouyedatu',
    'url' => '/index.php?v=listing&cid=225&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '435',
    'icon' => '',
  ),
  226 => 
  array (
    'name' => '杭州首页大图',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'hangzhoushouyedatu',
    'url' => '/index.php?v=listing&cid=226&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '213',
    'icon' => '',
  ),
  227 => 
  array (
    'name' => '首页顶通广告-杭州',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => '首页顶通广告-杭州',
    'url' => '/index.php?v=listing&cid=227&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '213',
    'icon' => '',
  ),
  228 => 
  array (
    'name' => '首页顶通广告-广州',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => '首页顶通广告-广州',
    'url' => '/index.php?v=listing&cid=228&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '326',
    'icon' => '',
  ),
  229 => 
  array (
    'name' => '首页顶通广告-深圳',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => '首页顶通广告-深圳',
    'url' => '/index.php?v=listing&cid=229&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '328',
    'icon' => '',
  ),
  230 => 
  array (
    'name' => '首页顶通广告-西安',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => '首页顶通广告-西安',
    'url' => '/index.php?v=listing&cid=230&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '435',
    'icon' => '',
  ),
  231 => 
  array (
    'name' => '首页顶通广告-北京',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => '首页顶通广告-北京',
    'url' => '/index.php?v=listing&cid=231&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '3360',
    'icon' => '',
  ),
  232 => 
  array (
    'name' => '首页顶通广告-上海',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => '首页顶通广告-上海',
    'url' => '/index.php?v=listing&cid=232&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '3361',
    'icon' => '',
  ),
  233 => 
  array (
    'name' => '首页顶通广告-天津',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => '首页顶通广告-天津',
    'url' => '/index.php?v=listing&cid=233&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '3362',
    'icon' => '',
  ),
  234 => 
  array (
    'name' => '首页推荐家具建材',
    'pid' => '0',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'shouyetuijianjiajujiancai',
    'url' => '/index.php?v=listing&cid=234&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  235 => 
  array (
    'name' => '建材类目一',
    'pid' => '234',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiancaileimuyi',
    'url' => '/index.php?v=listing&cid=235&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  236 => 
  array (
    'name' => '建材类目二',
    'pid' => '234',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiancaileimuer',
    'url' => '/index.php?v=listing&cid=236&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  237 => 
  array (
    'name' => '建材类目三',
    'pid' => '234',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiancaileimusan',
    'url' => '/index.php?v=listing&cid=237&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  238 => 
  array (
    'name' => '建材类目四',
    'pid' => '234',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiancaileimusi',
    'url' => '/index.php?v=listing&cid=238&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  239 => 
  array (
    'name' => '建材类目五',
    'pid' => '234',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiancaileimuwu',
    'url' => '/index.php?v=listing&cid=239&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  240 => 
  array (
    'name' => '建材类目六',
    'pid' => '234',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiancaileimuliu',
    'url' => '/index.php?v=listing&cid=240&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  241 => 
  array (
    'name' => '建材类目七',
    'pid' => '234',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiancaileimuqi',
    'url' => '/index.php?v=listing&cid=241&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  242 => 
  array (
    'name' => '预留栏目一',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'yuliulanmuyi',
    'url' => '/index.php?v=listing&cid=242&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  243 => 
  array (
    'name' => '预留栏目二',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'yuliulanmuer',
    'url' => '/index.php?v=listing&cid=243&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  244 => 
  array (
    'name' => '预留栏目三',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'yuliulanmusan',
    'url' => '/index.php?v=listing&cid=244&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  245 => 
  array (
    'name' => '首页装修课堂',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shouyezhuangxiuketang',
    'url' => '/index.php?v=listing&cid=245&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  246 => 
  array (
    'name' => '装修博览会',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhuangxiubolanhui',
    'url' => '/index.php?v=listing&cid=246&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  247 => 
  array (
    'name' => '装修公司活动聚合页',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shouyetuijianfengge',
    'url' => '/index.php?v=listing&cid=247&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  248 => 
  array (
    'name' => '真实用户案例01',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => ' zsyhal01',
    'url' => '/index.php?v=listing&cid=248&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  249 => 
  array (
    'name' => '真实用户案例02',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => ' zsyhal02',
    'url' => '/index.php?v=listing&cid=249&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  250 => 
  array (
    'name' => '真实用户案例03',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => ' zsyhal03',
    'url' => '/index.php?v=listing&cid=250&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  251 => 
  array (
    'name' => '业之峰',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'yzf',
    'url' => '/index.php?v=listing&cid=251&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  252 => 
  array (
    'name' => '发布营销活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => ' fbyxhd',
    'url' => '/index.php?v=listing&cid=252&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  253 => 
  array (
    'name' => '天津生活家',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => ' tianjinshenghuojia',
    'url' => '/index.php?v=listing&cid=253&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  254 => 
  array (
    'name' => '发布营销活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1040',
    'catdir' => 'fabuyingxiaohuodong',
    'url' => '/index.php?v=listing&cid=254&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  255 => 
  array (
    'name' => '首页大图—南京',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shouyedatunanjing',
    'url' => '/index.php?v=listing&cid=255&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '200',
    'icon' => '',
  ),
  256 => 
  array (
    'name' => '顶通广告—南京',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'dingtongguanggaonanjing',
    'url' => '/index.php?v=listing&cid=256&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '200',
    'icon' => '',
  ),
  257 => 
  array (
    'name' => 'U拍生活04',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'U拍生活04',
    'url' => '/index.php?v=listing&cid=257&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  258 => 
  array (
    'name' => 'U拍生活05',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'U拍生活05',
    'url' => '/index.php?v=listing&cid=258&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  259 => 
  array (
    'name' => '不忘初心',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'buwangchuxin',
    'url' => '/index.php?v=listing&cid=259&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  260 => 
  array (
    'name' => '爱书夫妻的文山书海简约生活',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'aishufuqidewenshanshuhaijianyu',
    'url' => '/index.php?v=listing&cid=260&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  270 => 
  array (
    'name' => '推荐位-装修案例',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1042',
    'catdir' => '推荐位-装修案例',
    'url' => '/index.php?v=listing&cid=270&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  271 => 
  array (
    'name' => '懒人装修',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'lanrenzhuangxiu',
    'url' => '/index.php?v=listing&cid=271&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  272 => 
  array (
    'name' => '家装分期',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jiazhuangfenqi',
    'url' => '/index.php?v=listing&cid=272&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  273 => 
  array (
    'name' => '管家介绍',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'guanjiajieshao',
    'url' => '/index.php?v=listing&cid=273&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  274 => 
  array (
    'name' => '婚房装修',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'hunfangzhuangxiu',
    'url' => '/index.php?v=listing&cid=274&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  275 => 
  array (
    'name' => '儿童房装修',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'ertongfangzhuangxiu',
    'url' => '/index.php?v=listing&cid=275&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  276 => 
  array (
    'name' => '全屋装修',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'quanwuzhuangxiu',
    'url' => '/index.php?v=listing&cid=276&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  277 => 
  array (
    'name' => '局部装修',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'jubuzhuangxiu',
    'url' => '/index.php?v=listing&cid=277&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  278 => 
  array (
    'name' => '装修课堂水电篇',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'zhuangxiuketangshuidianpian',
    'url' => '/index.php?v=listing&cid=278&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  279 => 
  array (
    'name' => '业主故事',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'yezhugushi',
    'url' => '/index.php?v=listing&cid=279&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  280 => 
  array (
    'name' => '北京家装节活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'beijingjiazhuangjiehuodong',
    'url' => '/index.php?v=listing&cid=280&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  281 => 
  array (
    'name' => '天津家装节活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'tianjinjiazhuangjiehuodong',
    'url' => '/index.php?v=listing&cid=281&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  282 => 
  array (
    'name' => '上海家装节活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shanghaijiazhuangjiehuodong',
    'url' => '/index.php?v=listing&cid=282&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  283 => 
  array (
    'name' => '杭州家装节活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'hangzhoujiazhuangjiehuodong',
    'url' => '/index.php?v=listing&cid=283&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  284 => 
  array (
    'name' => '西安家装节活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'xianjiazhuangjiehuodong',
    'url' => '/index.php?v=listing&cid=284&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  285 => 
  array (
    'name' => '广州家装节活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'guangzhoujiazhuangjiehuodong',
    'url' => '/index.php?v=listing&cid=285&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  286 => 
  array (
    'name' => '深圳家装节活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shenzhenjiazhuangjiehuodong',
    'url' => '/index.php?v=listing&cid=286&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  287 => 
  array (
    'name' => '南京家装节活动',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'nanjingjiazhuangjiehuodong',
    'url' => '/index.php?v=listing&cid=287&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  288 => 
  array (
    'name' => '其他内容（备用）',
    'pid' => '12',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'qitaneirong',
    'url' => '/index.php?v=listing&cid=288&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  289 => 
  array (
    'name' => '其他内容',
    'pid' => '12',
    'child' => '1',
    'modelid' => '1',
    'catdir' => '',
    'url' => '/index.php?v=listing&cid=289&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  290 => 
  array (
    'name' => '课堂视频',
    'pid' => '289',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'ketangshipin',
    'url' => '/index.php?v=listing&cid=290&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  291 => 
  array (
    'name' => '装修红宝书',
    'pid' => '12',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'zhuangxiuhongbaoshu',
    'url' => '/index.php?v=listing&cid=291&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  292 => 
  array (
    'name' => '第一章：施工准备',
    'pid' => '291',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'diyizhang',
    'url' => '/index.php?v=listing&cid=292&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  293 => 
  array (
    'name' => '第二章：材料选购与验收',
    'pid' => '291',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'dierzhangcailiaoxuangouyuyansh',
    'url' => '/index.php?v=listing&cid=293&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  294 => 
  array (
    'name' => '第三章：装修施工与质量验收',
    'pid' => '291',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'disanzhangzhuangxiushigongyuzh',
    'url' => '/index.php?v=listing&cid=294&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  295 => 
  array (
    'name' => '第四章：售后保修及环境保护',
    'pid' => '291',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'disizhangshouhoubaoxiujihuanji',
    'url' => '/index.php?v=listing&cid=295&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  296 => 
  array (
    'name' => '第五章：装修百问百答',
    'pid' => '291',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'diwuzhangzhuangxiubaiwenbaida',
    'url' => '/index.php?v=listing&cid=296&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  299 => 
  array (
    'name' => '业主故事',
    'pid' => '12',
    'child' => '1',
    'modelid' => '1',
    'catdir' => 'yezhugushi',
    'url' => '/index.php?v=listing&cid=299&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  300 => 
  array (
    'name' => '视频',
    'pid' => '299',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'shipin',
    'url' => '/index.php?v=listing&cid=300&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  301 => 
  array (
    'name' => '文章',
    'pid' => '299',
    'child' => '0',
    'modelid' => '1004',
    'catdir' => 'wenzhang',
    'url' => '/index.php?v=listing&cid=301&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  302 => 
  array (
    'name' => '顶通广告—武汉',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'dingtongguanggaowuhan',
    'url' => '/index.php?v=listing&cid=302&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '295',
    'icon' => '',
  ),
  303 => 
  array (
    'name' => '首页大图—南京',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shouyedatunanjing',
    'url' => '/index.php?v=listing&cid=303&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '295',
    'icon' => '',
  ),
  304 => 
  array (
    'name' => '顶通广告—郑州',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'dingtongguanggaozhengzhou',
    'url' => '/index.php?v=listing&cid=304&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '278',
    'icon' => '',
  ),
  305 => 
  array (
    'name' => '首页大图—郑州',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shouyedatuzhengzhou',
    'url' => '/index.php?v=listing&cid=305&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '278',
    'icon' => '',
  ),
  306 => 
  array (
    'name' => '首页大图—成都',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'shouyedatuchengdou',
    'url' => '/index.php?v=listing&cid=306&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '382',
    'icon' => '',
  ),
  307 => 
  array (
    'name' => '顶通广告—成都',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'dingtongguanggaochengdou',
    'url' => '/index.php?v=listing&cid=307&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '382',
    'icon' => '',
  ),
  308 => 
  array (
    'name' => '业主详情页',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'yezhuxiangqingye',
    'url' => '/index.php?v=listing&cid=308&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
  309 => 
  array (
    'name' => '二月大促',
    'pid' => '0',
    'child' => '0',
    'modelid' => '1',
    'catdir' => 'eryuedacu',
    'url' => '/index.php?v=listing&cid=309&page=1',
    'showloop' => '1',
    'type' => '0',
    'showhtml' => '0',
    'listhtml' => '0',
    'language' => '',
    'siteid' => '1',
    'icon' => '',
  ),
)?>