<?php
 return array (
  'cid' => '253',
  'siteid' => '1',
  'keyid' => 'content',
  'name' => '天津生活家',
  'mb' => '',
  'catdir' => ' tianjinshenghuojia',
  'parentdir' => '',
  'pid' => '0',
  'type' => '0',
  'child' => '0',
  'modelid' => '1',
  'sort' => '0',
  'domain' => '',
  'url' => '/index.php?v=listing&cid=253&page=1',
  'thumb' => '',
  'icon' => '',
  'workflowid' => '0',
  'showloop' => '1',
  'ismenu' => '1',
  'mshow' => '1',
  'listhtml' => '0',
  'showhtml' => '0',
  'listurl' => 'index.php?v=listing&cid={$cid}&page={$page}',
  'showurl' => 'index.php?v=show&cid={$cid}&id={$id}',
  'category_template' => '',
  'list_template' => 'uzhuang:shili',
  'show_template' => '',
  'seo_title' => '',
  'seo_keywords' => '',
  'seo_description' => '',
  'ishot' => '0',
)?>