<?php
 return array (
  'photos1' => 
  array (
    'id' => '5540',
    'modelid' => '1001',
    'field' => 'photos1',
    'name' => '平面图',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images2',
    'setting' => 
    array (
      'defaultvalue' => '',
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '1',
      'is_allow_show_img' => '1',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'photos2' => 
  array (
    'id' => '5541',
    'modelid' => '1001',
    'field' => 'photos2',
    'name' => '效果图',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images2',
    'setting' => 
    array (
      'defaultvalue' => '',
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '1',
      'is_allow_show_img' => '1',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'photos3' => 
  array (
    'id' => '5542',
    'modelid' => '1001',
    'field' => 'photos3',
    'name' => '竣工图',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images2',
    'setting' => 
    array (
      'defaultvalue' => '',
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '1',
      'is_allow_show_img' => '1',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'photos4' => 
  array (
    'id' => '5543',
    'modelid' => '1001',
    'field' => 'photos4',
    'name' => '户型图',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images2',
    'setting' => 
    array (
      'defaultvalue' => '',
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '1',
      'is_allow_show_img' => '1',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'title' => 
  array (
    'id' => '5028',
    'modelid' => '1001',
    'field' => 'title',
    'name' => '标题',
    'remark' => '',
    'css' => '',
    'minlength' => '2',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'title',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '1',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'villagename' => 
  array (
    'id' => '5135',
    'modelid' => '1001',
    'field' => 'villagename',
    'name' => '小区名称',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width: 270px; "  datatype="*" sucmsg="OK" errormsg="请填写正确的小区名称" nullmsg="请填写小区名称！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '2',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'companyid' => 
  array (
    'id' => '5145',
    'modelid' => '1001',
    'field' => 'companyid',
    'name' => '所属公司ID',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '2',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'designer' => 
  array (
    'id' => '5146',
    'modelid' => '1001',
    'field' => 'designer',
    'name' => '设计师',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box_sql',
    'setting' => 
    array (
      'sql' => 'SELECT `id`,`title` FROM `wz_company_team`  WHERE `status`=9 AND `companyid`=\'$companyid\'',
      'field_name' => 'title',
      'field_value' => 'id',
      'boxtype' => 'select',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '3',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'areaid' => 
  array (
    'id' => '5512',
    'modelid' => '1001',
    'field' => 'areaid',
    'name' => '城市',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => 
    array (
      'linkageid' => '1',
      'defaultvalue' => '',
    ),
    'ext_code' => 'datatype="*" sucmsg="OK" errormsg="请选择城市" nullmsg="请选择城市"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '4',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'thumb' => 
  array (
    'id' => '5023',
    'modelid' => '1001',
    'field' => 'thumb',
    'name' => '案例封面图',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 
    array (
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '1',
      'is_allow_show_img' => '0',
    ),
    'ext_code' => 'datatype="*" sucmsg="OK" errormsg="请上传缩略图" nullmsg="请上传缩略图！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '5',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'housetype' => 
  array (
    'id' => '5132',
    'modelid' => '1001',
    'field' => 'housetype',
    'name' => '户型',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '一居|1
二居|2
三居|3
四居|4
五居及以上|5
复式|6
别墅|7
公寓|8
四合院|13
其他|14',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'datatype="n" sucmsg="OK" errormsg="请选择户型" nullmsg="请选择户型！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '6',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'buildingtype' => 
  array (
    'id' => '5511',
    'modelid' => '1001',
    'field' => 'buildingtype',
    'name' => '装修类型',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '局部装修|1
旧房翻新|2
毛坯|3
精装修|4',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '',
      'outputtype' => '0',
    ),
    'ext_code' => 'datatype="n" sucmsg="OK" errormsg="请选择房屋类型" nullmsg="请选择房屋类型！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '6',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'style' => 
  array (
    'id' => '5131',
    'modelid' => '1001',
    'field' => 'style',
    'name' => '风格',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '现代|1
田园|3
中式|4
欧式|5
美式|6
日式|7
新古典|8
地中海|9
东南亚|10
混搭|11
其他|14',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'datatype="n" sucmsg="OK" errormsg="请选择风格" nullmsg="请选择风格！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '7',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'area' => 
  array (
    'id' => '5136',
    'modelid' => '1001',
    'field' => 'area',
    'name' => '面积',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '只填写数字，单位为㎡',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width: 150px; "  datatype="n" sucmsg="OK" errormsg="请输入正确的面积，只能为数字" nullmsg="请填写面积！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '9',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'cost' => 
  array (
    'id' => '5137',
    'modelid' => '1001',
    'field' => 'cost',
    'name' => '费用 (万元)',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '单位为万元(保留两位小数)',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '10',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'way' => 
  array (
    'id' => '5139',
    'modelid' => '1001',
    'field' => 'way',
    'name' => '装修方式',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '全包|1
半包|2',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '',
      'outputtype' => '0',
    ),
    'ext_code' => ' datatype="*" sucmsg="OK" errormsg="请选择装修方式" nullmsg="请选择装修方式！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '12',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'remark' => 
  array (
    'id' => '5025',
    'modelid' => '1001',
    'field' => 'remark',
    'name' => '设计思路',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 
    array (
      'defaultvalue' => '',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '14',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'collection' => 
  array (
    'id' => '5143',
    'modelid' => '1001',
    'field' => 'collection',
    'name' => '收藏数',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '15',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'addtime' => 
  array (
    'id' => '5015',
    'modelid' => '1001',
    'field' => 'addtime',
    'name' => '创建时间',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'int',
      'format' => 'Y-m-d H:i:s',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'block' => 
  array (
    'id' => '5016',
    'modelid' => '1001',
    'field' => 'block',
    'name' => '添加到区块',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'block',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'groups' => 
  array (
    'id' => '5017',
    'modelid' => '1001',
    'field' => 'groups',
    'name' => '用户组权限',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'group',
    'setting' => 
    array (
      'groups' => '4,5',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '2',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'url' => 
  array (
    'id' => '5018',
    'modelid' => '1001',
    'field' => 'url',
    'name' => '链接地址',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'url',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'sort' => 
  array (
    'id' => '5019',
    'modelid' => '1001',
    'field' => 'sort',
    'name' => '权重',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '255',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'slider',
    'setting' => 
    array (
      'defaultvalue' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'template' => 
  array (
    'id' => '5020',
    'modelid' => '1001',
    'field' => 'template',
    'name' => '内容页模板',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'template',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'allowcomment' => 
  array (
    'id' => '5021',
    'modelid' => '1001',
    'field' => 'allowcomment',
    'name' => '允许评论',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '允许|1
不允许|0',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '2',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'status' => 
  array (
    'id' => '5022',
    'modelid' => '1001',
    'field' => 'status',
    'name' => '稿件状态',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '通过审核|9
待审|1
草稿|6',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '9',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'relation' => 
  array (
    'id' => '5024',
    'modelid' => '1001',
    'field' => 'relation',
    'name' => '相关内容',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'relation',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'keywords' => 
  array (
    'id' => '5029',
    'modelid' => '1001',
    'field' => 'keywords',
    'name' => '关键词',
    'remark' => '多关键词之间用半角逗号“,”隔开',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'keyword',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
  'cid' => 
  array (
    'id' => '5027',
    'modelid' => '1001',
    'field' => 'cid',
    'name' => '所属栏目',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请选择栏目',
    'formtype' => 'cid',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '100',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
  ),
)?>