<?php
 return array (
  'companyid' => 
  array (
    'id' => '5412',
    'modelid' => '1028',
    'field' => 'companyid',
    'name' => '所属公司id',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'villagename' => 
  array (
    'id' => '5413',
    'modelid' => '1028',
    'field' => 'villagename',
    'name' => '小区名称',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width:250px;" datatype="*" sucmsg="OK" errormsg="请填写正确的小区名称" nullmsg="请填写小区名称！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'photos1' => 
  array (
    'id' => '5437',
    'modelid' => '1028',
    'field' => 'photos1',
    'name' => '图集1',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images2',
    'setting' => 
    array (
      'defaultvalue' => '',
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '0',
      'is_allow_show_img' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'photos2' => 
  array (
    'id' => '5438',
    'modelid' => '1028',
    'field' => 'photos2',
    'name' => '图集2',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images2',
    'setting' => 
    array (
      'defaultvalue' => '',
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '0',
      'is_allow_show_img' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'photos3' => 
  array (
    'id' => '5439',
    'modelid' => '1028',
    'field' => 'photos3',
    'name' => '图集3',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'images2',
    'setting' => 
    array (
      'defaultvalue' => '',
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '0',
      'is_allow_show_img' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'designer' => 
  array (
    'id' => '5414',
    'modelid' => '1028',
    'field' => 'designer',
    'name' => '设计师',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box_sql',
    'setting' => 
    array (
      'sql' => 'SELECT `id`,`title` FROM `wz_company_team`  WHERE `status`=9 AND `companyid`=\'$companyid\'',
      'field_name' => 'title',
      'field_value' => 'id',
      'boxtype' => 'select',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '2',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'housetype' => 
  array (
    'id' => '5415',
    'modelid' => '1028',
    'field' => 'housetype',
    'name' => '户型',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '一居|1
二居|2
三居|3
四居|4
五居|5
复式|6
别墅|7
公寓|8
跃层|9
loft|10
联排|11
独栋|12
四合院|13
其他|14',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'datatype="n" sucmsg="OK" errormsg="请选择户型" nullmsg="请选择户型！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '3',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'style' => 
  array (
    'id' => '5416',
    'modelid' => '1028',
    'field' => 'style',
    'name' => '风格',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '现代|1
简约|2
田园|3
中式|4
欧式|5
美式|6
日式|7
新古典|8
地中海|9
东南亚|10
混搭|11
民族风|12
工业风|13
其他|14',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'datatype="n" sucmsg="OK" errormsg="请选择风格" nullmsg="请选择风格！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '3',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'buildingtype' => 
  array (
    'id' => '5417',
    'modelid' => '1028',
    'field' => 'buildingtype',
    'name' => '房屋类型',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '局部装修|1
旧房翻新|2
毛坯|3
精装修|4',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'datatype="n" sucmsg="OK" errormsg="请选择房屋类型" nullmsg="请选择房屋类型！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '3',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'area' => 
  array (
    'id' => '5418',
    'modelid' => '1028',
    'field' => 'area',
    'name' => '面积',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => ' 只填写数字，单位为㎡',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width: 150px; "  datatype="n" sucmsg="OK" errormsg="请输入正确的面积，只能为数字" nullmsg="请填写面积！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '4',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'cost' => 
  array (
    'id' => '5419',
    'modelid' => '1028',
    'field' => 'cost',
    'name' => '费用',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '只填写数字，单位为元。',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width: 150px; "  datatype="n" sucmsg="OK" errormsg="请输入正确的费用，只能为数字" nullmsg="请填写费用！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '4',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'way' => 
  array (
    'id' => '5420',
    'modelid' => '1028',
    'field' => 'way',
    'name' => '装修方式',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '全包|1
半包|2',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '5',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'areaid' => 
  array (
    'id' => '5519',
    'modelid' => '1028',
    'field' => 'areaid',
    'name' => '城市',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => 
    array (
      'linkageid' => '1',
      'defaultvalue' => '0',
    ),
    'ext_code' => ' datatype="*" sucmsg="OK" errormsg="请选择城市" nullmsg="请选择城市！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '5',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'thumb' => 
  array (
    'id' => '5387',
    'modelid' => '1028',
    'field' => 'thumb',
    'name' => '缩略图',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 
    array (
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '1',
      'is_allow_show_img' => '0',
    ),
    'ext_code' => ' datatype="*" sucmsg="OK" errormsg="请上传缩略图" nullmsg="请上传缩略图！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '6',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'content' => 
  array (
    'id' => '5421',
    'modelid' => '1028',
    'field' => 'content',
    'name' => '设计思路',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 
    array (
      'toolbar' => 'textarea',
      'defaultvalue' => '',
      'enablesaveimage' => '0',
      'watermark_enable' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '6',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'cid' => 
  array (
    'id' => '5391',
    'modelid' => '1028',
    'field' => 'cid',
    'name' => '所属栏目',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请选择栏目',
    'formtype' => 'cid',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '7',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'title' => 
  array (
    'id' => '5392',
    'modelid' => '1028',
    'field' => 'title',
    'name' => '标题',
    'remark' => '',
    'css' => '',
    'minlength' => '2',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '请输入标题',
    'formtype' => 'title',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '8',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'keywords' => 
  array (
    'id' => '5393',
    'modelid' => '1028',
    'field' => 'keywords',
    'name' => '关键词',
    'remark' => '多关键词之间用半角逗号“,”隔开',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'keyword',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '9',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'remark' => 
  array (
    'id' => '5389',
    'modelid' => '1028',
    'field' => 'remark',
    'name' => '摘要',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 
    array (
      'defaultvalue' => '',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '10',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'block' => 
  array (
    'id' => '5380',
    'modelid' => '1028',
    'field' => 'block',
    'name' => '添加到区块',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'block',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '11',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'url' => 
  array (
    'id' => '5382',
    'modelid' => '1028',
    'field' => 'url',
    'name' => '链接地址',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'url',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '11',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'relation' => 
  array (
    'id' => '5388',
    'modelid' => '1028',
    'field' => 'relation',
    'name' => '相关内容',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'relation',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '11',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'addtime' => 
  array (
    'id' => '5379',
    'modelid' => '1028',
    'field' => 'addtime',
    'name' => '添加时间',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'int',
      'format' => 'Y-m-d H:i:s',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '12',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'allowcomment' => 
  array (
    'id' => '5385',
    'modelid' => '1028',
    'field' => 'allowcomment',
    'name' => '允许评论',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '允许|1
不允许|0',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '2',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '17',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'groups' => 
  array (
    'id' => '5381',
    'modelid' => '1028',
    'field' => 'groups',
    'name' => '用户组权限',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'group',
    'setting' => 
    array (
      'groups' => '4,5',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '2',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '18',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'sort' => 
  array (
    'id' => '5383',
    'modelid' => '1028',
    'field' => 'sort',
    'name' => '权重',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '255',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'slider',
    'setting' => 
    array (
      'defaultvalue' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '20',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'time' => 
  array (
    'id' => '5422',
    'modelid' => '1028',
    'field' => 'time',
    'name' => '创建时间',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'datetime',
      'format' => 'Y-m-d Ah:i:s',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '20',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'template' => 
  array (
    'id' => '5384',
    'modelid' => '1028',
    'field' => 'template',
    'name' => '内容页模板',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'template',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '21',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
  'status' => 
  array (
    'id' => '5386',
    'modelid' => '1028',
    'field' => 'status',
    'name' => '稿件状态',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '通过审核|9
待审|1
定时发送|8
草稿|6',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '9',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '30',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
  ),
)?>