<?php
 return array (
  'browse' => 
  array (
    'id' => '5833',
    'modelid' => '1000',
    'field' => 'browse',
    'name' => '浏览量1',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'cid' => 
  array (
    'id' => '5012',
    'modelid' => '1000',
    'field' => 'cid',
    'name' => '所属栏目',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请选择栏目',
    'formtype' => 'cid',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '1',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'title' => 
  array (
    'id' => '5013',
    'modelid' => '1000',
    'field' => 'title',
    'name' => '公司名称',
    'remark' => '',
    'css' => '',
    'minlength' => '2',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'title',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '2',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'id' => 
  array (
    'id' => '5075',
    'modelid' => '1000',
    'field' => 'id',
    'name' => '所属用户ID',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => ' datatype="n" sucmsg="OK" errormsg="请填写所属用户ID" nullmsg="请填写所属用户ID"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '2',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'areaid' => 
  array (
    'id' => '5064',
    'modelid' => '1000',
    'field' => 'areaid',
    'name' => '公司详细地址',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => 
    array (
      'linkageid' => '1',
      'defaultvalue' => '2,3360',
    ),
    'ext_code' => ' datatype="*" sucmsg="OK" errormsg="请选择公司地址" nullmsg="请选择公司地址"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '3',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'address' => 
  array (
    'id' => '5067',
    'modelid' => '1000',
    'field' => 'address',
    'name' => '呵呵',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => ' datatype="*5-200" sucmsg="OK" errormsg="请填写公司详细地址" nullmsg="公司详细地址最少5个字符！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '4',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'companylogo' => 
  array (
    'id' => '5190',
    'modelid' => '1000',
    'field' => 'companylogo',
    'name' => '页面LOGO',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 
    array (
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '0',
      'is_allow_show_img' => '1',
    ),
    'ext_code' => ' datatype="*" sucmsg="OK" errormsg="请上传页面LOGO" nullmsg="请上传页面LOGO！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '5',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'thumb' => 
  array (
    'id' => '5008',
    'modelid' => '1000',
    'field' => 'thumb',
    'name' => '公司logo',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 
    array (
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '0',
      'is_allow_show_img' => '1',
    ),
    'ext_code' => ' datatype="*" sucmsg="OK" errormsg="请上传公司logo" nullmsg="请上传公司logo！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '5',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'domain' => 
  array (
    'id' => '5104',
    'modelid' => '1000',
    'field' => 'domain',
    'name' => '公司二级域名',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '6',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'areaids' => 
  array (
    'id' => '5077',
    'modelid' => '1000',
    'field' => 'areaids',
    'name' => '服务区域',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage_box',
    'setting' => 
    array (
      'formfield' => 'LK1_2',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '11',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'tese' => 
  array (
    'id' => '5066',
    'modelid' => '1000',
    'field' => 'tese',
    'name' => '特色服务',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '装修0增项|1
环保装修|2
10年质保|3
装修管家服务|4
免费量房|5',
      'boxtype' => 'checkbox',
      'fieldtype' => 'varchar',
      'minnumber' => '1',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '15',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'typeids' => 
  array (
    'id' => '5076',
    'modelid' => '1000',
    'field' => 'typeids',
    'name' => '类型',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '普通住宅|1
小户型|2
别墅|3
局部装修|4',
      'boxtype' => 'checkbox',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => ' datatype="max6" sucmsg="OK" errormsg="请选择类型" nullmsg="请选择类型！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '16',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'style' => 
  array (
    'id' => '5065',
    'modelid' => '1000',
    'field' => 'style',
    'name' => '专长风格',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '现代|1
美式|2
欧式|3
中式|4
混搭|5
田园|6
地中海|7
简约|8
东南亚|9
日式|10
北欧|11
简欧|12',
      'boxtype' => 'checkbox',
      'fieldtype' => 'varchar',
      'defaultvalue' => '',
      'outputtype' => '0',
    ),
    'ext_code' => ' datatype="max6" sucmsg="OK" errormsg="请选择专长风格" nullmsg="请选择专长风格！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '17',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'content' => 
  array (
    'id' => '5011',
    'modelid' => '1000',
    'field' => 'content',
    'name' => '公司简介',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 
    array (
      'toolbar' => 'full',
      'defaultvalue' => '',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '21',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'check_cert' => 
  array (
    'id' => '5074',
    'modelid' => '1000',
    'field' => 'check_cert',
    'name' => '营业执照',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '未认证|0
已认证|1',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '21',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'check_company' => 
  array (
    'id' => '5072',
    'modelid' => '1000',
    'field' => 'check_company',
    'name' => '认证公司',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '未认证|0
已认证|1',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '22',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'check_money' => 
  array (
    'id' => '5073',
    'modelid' => '1000',
    'field' => 'check_money',
    'name' => '保证金',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '未缴纳|0
已缴纳|1',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '23',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'avg_total' => 
  array (
    'id' => '5069',
    'modelid' => '1000',
    'field' => 'avg_total',
    'name' => '综合评分',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '40',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'avg_design' => 
  array (
    'id' => '5070',
    'modelid' => '1000',
    'field' => 'avg_design',
    'name' => '设计水平',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '41',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'avg_service' => 
  array (
    'id' => '5071',
    'modelid' => '1000',
    'field' => 'avg_service',
    'name' => '服务态度',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '42',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'avg_quality' => 
  array (
    'id' => '5105',
    'modelid' => '1000',
    'field' => 'avg_quality',
    'name' => '施工质量',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '43',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'order_numbers' => 
  array (
    'id' => '5068',
    'modelid' => '1000',
    'field' => 'order_numbers',
    'name' => '已完成案例数',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'number',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '44',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'block' => 
  array (
    'id' => '5001',
    'modelid' => '1000',
    'field' => 'block',
    'name' => '添加到区块',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'block',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '49',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'url' => 
  array (
    'id' => '5003',
    'modelid' => '1000',
    'field' => 'url',
    'name' => '链接地址',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'url',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'remark' => 
  array (
    'id' => '5010',
    'modelid' => '1000',
    'field' => 'remark',
    'name' => '摘要',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 
    array (
      'defaultvalue' => '',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'addtime' => 
  array (
    'id' => '5000',
    'modelid' => '1000',
    'field' => 'addtime',
    'name' => '添加时间',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'int',
      'format' => 'Y-m-d H:i:s',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '51',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'allowcomment' => 
  array (
    'id' => '5006',
    'modelid' => '1000',
    'field' => 'allowcomment',
    'name' => '允许评论',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '允许|1
不允许|0',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '2',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '52',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'groups' => 
  array (
    'id' => '5002',
    'modelid' => '1000',
    'field' => 'groups',
    'name' => '用户组权限',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'group',
    'setting' => 
    array (
      'groups' => '4,5',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '2',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '53',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'sort' => 
  array (
    'id' => '5004',
    'modelid' => '1000',
    'field' => 'sort',
    'name' => '权重',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '255',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'slider',
    'setting' => 
    array (
      'defaultvalue' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '54',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'template' => 
  array (
    'id' => '5005',
    'modelid' => '1000',
    'field' => 'template',
    'name' => '内容页模板',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'template',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '55',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
  'status' => 
  array (
    'id' => '5007',
    'modelid' => '1000',
    'field' => 'status',
    'name' => '稿件状态',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '通过审核|9
待审|1
草稿|6',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '9',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '60',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'company',
    'attr_table' => 'company_data',
  ),
)?>