<?php
 return array (
  'order_no' => 
  array (
    'id' => '5165',
    'modelid' => '1002',
    'field' => 'order_no',
    'name' => '订单号',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'disabled="disabled"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'name' => 
  array (
    'id' => '5488',
    'modelid' => '1002',
    'field' => 'name',
    'name' => '姓名',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => ' style="width: 251px; "',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'community' => 
  array (
    'id' => '5499',
    'modelid' => '1002',
    'field' => 'community',
    'name' => '所在小区',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width: 250px; " ',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'uid' => 
  array (
    'id' => '5524',
    'modelid' => '1002',
    'field' => 'uid',
    'name' => '用户',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box_sql',
    'setting' => 
    array (
      'sql' => 'SELECT    *  FROM `wz_member`   ORDER BY uid DESC  limit 0,8',
      'field_name' => 'username',
      'field_value' => 'uid',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'sex' => 
  array (
    'id' => '5564',
    'modelid' => '1002',
    'field' => 'sex',
    'name' => '性别',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '男|男
女|女',
      'boxtype' => 'radio',
      'fieldtype' => 'varchar',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'progress' => 
  array (
    'id' => '5193',
    'modelid' => '1002',
    'field' => 'progress',
    'name' => '施工阶段',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '已申请量房|1
已分配公司|2
装修施工中|3
订单已完结|4',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '1',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'title' => 
  array (
    'id' => '5043',
    'modelid' => '1002',
    'field' => 'title',
    'name' => '您的姓名',
    'remark' => '',
    'css' => '',
    'minlength' => '2',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '2',
    'formtype' => 'title',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '1',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'telephone' => 
  array (
    'id' => '5108',
    'modelid' => '1002',
    'field' => 'telephone',
    'name' => '手机',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'placeholder="请输入手机号码" datatype="m" sucmsg="OK" errormsg="请输入正确的手机号码" nullmsg="请填写手机号码！"style="width: 142px; "',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '2',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'areaid' => 
  array (
    'id' => '5106',
    'modelid' => '1002',
    'field' => 'areaid',
    'name' => '城市区域',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => 
    array (
      'linkageid' => '1',
      'defaultvalue' => '2,3360',
    ),
    'ext_code' => 'datatype="n" sucmsg="OK" errormsg="请选择城市区域" nullmsg="请选择城市区域！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '3',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'address' => 
  array (
    'id' => '5109',
    'modelid' => '1002',
    'field' => 'address',
    'name' => '详细地址',
    'remark' => '请填写地址',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'datatype="" sucmsg="OK" errormsg="请填写详细地址" nullmsg="请填写详细地址！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '6',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'xqmc' => 
  array (
    'id' => '5563',
    'modelid' => '1002',
    'field' => 'xqmc',
    'name' => '小区名称',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '7',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'housecategory' => 
  array (
    'id' => '5110',
    'modelid' => '1002',
    'field' => 'housecategory',
    'name' => '房屋类别',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '现 房 新 房|1
期 房 新 房|2
二 手 房|3',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'onchange="empSexChange(this.value)"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '7',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'renovation' => 
  array (
    'id' => '5113',
    'modelid' => '1002',
    'field' => 'renovation',
    'name' => '装修类型',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '毛坯装修|1
改造型装修|2',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'onchange="empSexChange(this.value)" <font color:"red">*</fond>',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '8',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'renovationcategory' => 
  array (
    'id' => '5115',
    'modelid' => '1002',
    'field' => 'renovationcategory',
    'name' => '装修类别',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '家           装|1
公           装|2',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'style="width:150px" placeholder="装修类别" datatype="n" sucmsg="OK" errormsg="请输入正确的装修类别" nullmsg="请填写装修类别！"  onclick="change_formtype(this.value)" ',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '9',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'homestyle' => 
  array (
    'id' => '5129',
    'modelid' => '1002',
    'field' => 'homestyle',
    'name' => '房屋户型',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '小 户 型|1
一     居|2
二     居|3
三     居|4
四     居|5
五     居|6
六居以上|7
复式|8
别墅|9
公寓|10
跃层|11
庭院|12
错层|13
四合院|14
loft|15
叠加|16
独栋|17
联排|18
局部装修|19',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'minnumber' => '-1',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'onchange="empSexChange(this.value)"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '10',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'housetype' => 
  array (
    'id' => '5117',
    'modelid' => '1002',
    'field' => 'housetype',
    'name' => '房屋类别',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '办       公|1
k   t    v  |2
餐       饮|3
商       铺|4
美容美发|5
展       厅|6
酒       吧|7
连锁店面|8
局部装修|9
其他装修|10',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'onchange="empSexChange(this.value)" <font color="red">*</font>',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '10',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'style' => 
  array (
    'id' => '5119',
    'modelid' => '1002',
    'field' => 'style',
    'name' => '装修风格',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '欧式|1
美式|2
新古典|3
中式|4
新中式|5
田园|6
现代|7
地中海|8
东南亚|9
日式|10
混搭|11
其他|12',
      'boxtype' => 'checkbox',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'datatype="n" sucmsg="OK" errormsg="请选择装修风格" nullmsg="请选择装修风格！"  onClick="doCheck(this)"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '11',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'addtime' => 
  array (
    'id' => '5030',
    'modelid' => '1002',
    'field' => 'addtime',
    'name' => '添加时间',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'int',
      'format' => 'Y-m-d H:i:s',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '12',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'area' => 
  array (
    'id' => '5120',
    'modelid' => '1002',
    'field' => 'area',
    'name' => '房屋面积',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width: 142px; " ',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '13',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'way' => 
  array (
    'id' => '5121',
    'modelid' => '1002',
    'field' => 'way',
    'name' => '装修方式',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '全包|1
半包|2
待定|3
套餐|4
定制|5',
      'boxtype' => 'radio',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'placeholder="装修方式" datatype="n" sucmsg="OK" errormsg="请输入正确的装修方式" nullmsg="请填写装修方式！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '14',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'budget' => 
  array (
    'id' => '5496',
    'modelid' => '1002',
    'field' => 'budget',
    'name' => '装修预算',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '15',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width: 142px; "',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '15',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'iscompany' => 
  array (
    'id' => '5125',
    'modelid' => '1002',
    'field' => 'iscompany',
    'name' => '已选定公司？',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '未选定公司|1
已选定公司|2',
      'boxtype' => 'radio',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => 'datatype="n" sucmsg="OK" errormsg="请选择是否选的装修公司" nullmsg="请选择是否选的装修公司！"  onclick="change_formtype2(this.value)"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '16',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'referrals' => 
  array (
    'id' => '5497',
    'modelid' => '1002',
    'field' => 'referrals',
    'name' => '推荐人姓名',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width: 142px; "',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '16',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'yxgsm' => 
  array (
    'id' => '5227',
    'modelid' => '1002',
    'field' => 'yxgsm',
    'name' => '已选定公司名',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => ' datatype="*" sucmsg="OK" errormsg="请输入已选定公司名" nullmsg="请输入已选定公司名"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '17',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'referral' => 
  array (
    'id' => '5498',
    'modelid' => '1002',
    'field' => 'referral',
    'name' => '推荐人手机号',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width: 142px; "',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '17',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'leadtime' => 
  array (
    'id' => '5126',
    'modelid' => '1002',
    'field' => 'leadtime',
    'name' => '交房时间',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'date',
      'format' => 'Y-m-d Ah:i:s',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '18',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'decorationtime' => 
  array (
    'id' => '5127',
    'modelid' => '1002',
    'field' => 'decorationtime',
    'name' => '装修时间',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'date',
      'format' => 'Y-m-d Ah:i:s',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '19',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'content' => 
  array (
    'id' => '5130',
    'modelid' => '1002',
    'field' => 'content',
    'name' => '装修要求',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'editor',
    'setting' => 
    array (
      'toolbar' => 'textarea',
      'defaultvalue' => '',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '20',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'source' => 
  array (
    'id' => '5128',
    'modelid' => '1002',
    'field' => 'source',
    'name' => '来源',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '21',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'status' => 
  array (
    'id' => '5037',
    'modelid' => '1002',
    'field' => 'status',
    'name' => '状态',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '通过审核|9
待审|1
草稿|6',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '9',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '30',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'url' => 
  array (
    'id' => '5033',
    'modelid' => '1002',
    'field' => 'url',
    'name' => '链接地址',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'url',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'template' => 
  array (
    'id' => '5035',
    'modelid' => '1002',
    'field' => 'template',
    'name' => '内容页模板',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'template',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'thumb' => 
  array (
    'id' => '5038',
    'modelid' => '1002',
    'field' => 'thumb',
    'name' => '缩略图',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 
    array (
      'upload_allowext' => 'gif|jpg|jpeg|png|bmp',
      'is_water' => '0',
      'is_allow_show_img' => '1',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'cid' => 
  array (
    'id' => '5042',
    'modelid' => '1002',
    'field' => 'cid',
    'name' => '所属栏目',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请选择栏目',
    'formtype' => 'cid',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'sort' => 
  array (
    'id' => '5107',
    'modelid' => '1002',
    'field' => 'sort',
    'name' => '排序',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '50',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'referer' => 
  array (
    'id' => '5189',
    'modelid' => '1002',
    'field' => 'referer',
    'name' => '来源页面',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '60',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
  'kfzy' => 
  array (
    'id' => '5554',
    'modelid' => '1002',
    'field' => 'kfzy',
    'name' => ' 客服专用',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 
    array (
      'defaultvalue' => '',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '61',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'demand',
    'attr_table' => '',
  ),
)?>