<?php
 return array (
  'name' => 
  array (
    'id' => '5482',
    'modelid' => '10',
    'field' => 'name',
    'name' => '姓名',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '10',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '15',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '<input type="text" nullmsg=“" errormsg="" sucmsg="OK" datatype="" style="width: 142px; "',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'nickname' => 
  array (
    'id' => '5489',
    'modelid' => '10',
    'field' => 'nickname',
    'name' => '昵称',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '20',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '10',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '<input type="text" nullmsg="" errormsg="" sucmsg="OK" datatype="" style="width: 142px; "',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'city' => 
  array (
    'id' => '5491',
    'modelid' => '10',
    'field' => 'city',
    'name' => '所在城市',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'linkage',
    'setting' => 
    array (
      'linkageid' => '1',
      'defaultvalue' => '23360',
    ),
    'ext_code' => 'datatype="n" sucmsg="OK" errormsg="请选择城市区域" nullmsg="请选择城市区域！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'detailed' => 
  array (
    'id' => '5494',
    'modelid' => '10',
    'field' => 'detailed',
    'name' => '详细地址',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'truename' => 
  array (
    'id' => '400',
    'modelid' => '10',
    'field' => 'truename',
    'name' => '真实姓名',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'sex' => 
  array (
    'id' => '402',
    'modelid' => '10',
    'field' => 'sex',
    'name' => '性别',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '男|1
女|0',
      'boxtype' => 'radio',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'pic' => 
  array (
    'id' => '5274',
    'modelid' => '10',
    'field' => 'pic',
    'name' => '单图',
    'remark' => '添加图片',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'image',
    'setting' => 
    array (
      'upload_allowext' => '',
      'is_water' => '0',
      'is_allow_show_img' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'shopuid' => 
  array (
    'id' => '5534',
    'modelid' => '10',
    'field' => 'shopuid',
    'name' => '商户id',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'remark' => 
  array (
    'id' => '5553',
    'modelid' => '10',
    'field' => 'remark',
    'name' => '个人信息',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '0',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '1',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'age' => 
  array (
    'id' => '5479',
    'modelid' => '10',
    'field' => 'age',
    'name' => '年龄',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'style="width: 142px; "',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '1',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'birthday' => 
  array (
    'id' => '399',
    'modelid' => '10',
    'field' => 'birthday',
    'name' => '出生日期',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'date',
      'format' => 'Y-m-d Ah:i:s',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '2',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'constellation' => 
  array (
    'id' => '5481',
    'modelid' => '10',
    'field' => 'constellation',
    'name' => '星座',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '请 选 择|0
白 羊 座|1
金 牛 座|2
双 子 座|3
巨 蟹 座|4
狮 子 座|5
处 女 座|6
天 秤 座|7
天 蝎 座|8
射 手 座|9
摩 羯 座|10
水 瓶 座|11
双 鱼 座|12',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '3',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'marriage' => 
  array (
    'id' => '403',
    'modelid' => '10',
    'field' => 'marriage',
    'name' => '婚姻',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '已婚|1
未婚|0',
      'boxtype' => 'radio',
      'fieldtype' => 'varchar',
      'defaultvalue' => '',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '4',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'baby' => 
  array (
    'id' => '5483',
    'modelid' => '10',
    'field' => 'baby',
    'name' => '是否有宝宝',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '请选择|0
暂时没有|1
1个宝宝|2
2个及更多宝宝|3',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '5',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'dwelling' => 
  array (
    'id' => '5485',
    'modelid' => '10',
    'field' => 'dwelling',
    'name' => '居住状态',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '请选择|0
准备购房|1
打算装修|2
装修中|3
逛一逛|4',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '6',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'Budget' => 
  array (
    'id' => '5486',
    'modelid' => '10',
    'field' => 'Budget',
    'name' => '装修预算',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '请选择|0
2万以下|1
2-4万|2
4-6万|3
6-10万|4
10-15万|5
15-20万|6
20万以上|7',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '1',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '7',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
  'attention' => 
  array (
    'id' => '5487',
    'modelid' => '10',
    'field' => 'attention',
    'name' => '我最关注',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '环保安全 |1
口碑评论 |2
品牌荣誉 |3
海量选择 |4
靠谱实惠 |5
服务保障 |6',
      'boxtype' => 'checkbox',
      'fieldtype' => 'varchar',
      'defaultvalue' => '0',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '8',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'member',
    'attr_table' => 'member_detail_data',
  ),
)?>