<?php
 return array (
  'starttime' => 
  array (
    'id' => '5182',
    'modelid' => '1006',
    'field' => 'starttime',
    'name' => '保险开始时间',
    'remark' => '',
    'css' => '',
    'minlength' => '8',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'date',
      'format' => 'Y-m-d H:i:s',
    ),
    'ext_code' => 'datatype="*" sucmsg="OK" errormsg="请选保险开始时间" nullmsg="请选保险开始时间！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
  'zxtime' => 
  array (
    'id' => '5183',
    'modelid' => '1006',
    'field' => 'zxtime',
    'name' => '装修开始日期',
    'remark' => '',
    'css' => '',
    'minlength' => '8',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'date',
      'format' => 'Y-m-d Ah:i:s',
    ),
    'ext_code' => 'datatype="*" sucmsg="OK" errormsg="请选装修开始日期" nullmsg="请选装修开始日期！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
  'order_no' => 
  array (
    'id' => '5184',
    'modelid' => '1006',
    'field' => 'order_no',
    'name' => '订单编号',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box_sql',
    'setting' => 
    array (
      'sql' => 'SELECT `order_no` FROM `wz_demand` WHERE `publisher`=\'$publisher\' ORDER BY `id` DESC',
      'field_name' => 'order_no',
      'field_value' => 'order_no',
      'boxtype' => 'select',
      'fieldtype' => 'varchar',
      'defaultvalue' => '',
      'outputtype' => '0',
    ),
    'ext_code' => 'datatype="n5-20" sucmsg="OK" errormsg="请选择订单编号" nullmsg="请选择订单编号！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
  'idcard' => 
  array (
    'id' => '5185',
    'modelid' => '1006',
    'field' => 'idcard',
    'name' => '身份证号',
    'remark' => '',
    'css' => '',
    'minlength' => '15',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'datatype="idcard" nullmsg="请填写身份证号码！" errormsg="您填写的身份证号码不对！" ',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
  'mobile' => 
  array (
    'id' => '5186',
    'modelid' => '1006',
    'field' => 'mobile',
    'name' => '手机号',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '请输入手机号码',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'datatype="m" sucmsg="OK" errormsg="请输入正确的手机号码" nullmsg="请填写信息！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
  'address' => 
  array (
    'id' => '5187',
    'modelid' => '1006',
    'field' => 'address',
    'name' => '房屋地址',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'textarea',
    'setting' => 
    array (
      'defaultvalue' => '',
      'enablehtml' => '0',
    ),
    'ext_code' => 'datatype="*" sucmsg="OK" errormsg="请填写房屋地址" nullmsg="请填写房屋地址！"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
  'email' => 
  array (
    'id' => '5226',
    'modelid' => '1006',
    'field' => 'email',
    'name' => '邮箱',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'text',
    'setting' => 
    array (
      'size' => '',
      'defaultvalue' => '',
      'placeholder' => '',
      'ispassword' => '0',
      'enablehtml' => '0',
    ),
    'ext_code' => 'datatype="e" sucmsg="OK" errormsg="请填写正确的邮箱" nullmsg="请填写邮箱"',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '0',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '1',
    'to_fulltext' => '1',
    'to_block' => '0',
    'sort' => '0',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
  'cid' => 
  array (
    'id' => '5179',
    'modelid' => '1006',
    'field' => 'cid',
    'name' => '所属栏目',
    'remark' => '',
    'css' => '',
    'minlength' => '1',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '请选择栏目',
    'formtype' => 'cid',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '1',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
  'title' => 
  array (
    'id' => '5180',
    'modelid' => '1006',
    'field' => 'title',
    'name' => '被保险人姓名',
    'remark' => '',
    'css' => '',
    'minlength' => '2',
    'maxlength' => '80',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'title',
    'setting' => '',
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '5',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '1',
    'to_block' => '1',
    'sort' => '2',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
  'addtime' => 
  array (
    'id' => '5167',
    'modelid' => '1006',
    'field' => 'addtime',
    'name' => '添加时间',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'datetime',
    'setting' => 
    array (
      'fieldtype' => 'int',
      'format' => 'Y-m-d H:i:s',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '1',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '1',
    'sort' => '12',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
  'status' => 
  array (
    'id' => '5174',
    'modelid' => '1006',
    'field' => 'status',
    'name' => '稿件状态',
    'remark' => '',
    'css' => '',
    'minlength' => '0',
    'maxlength' => '0',
    'pattern' => '',
    'errortips' => '',
    'formtype' => 'box',
    'setting' => 
    array (
      'options' => '通过审核|9
待审|1
草稿|6',
      'boxtype' => 'radio',
      'fieldtype' => 'tinyint',
      'minnumber' => '1',
      'defaultvalue' => '9',
      'outputtype' => '0',
    ),
    'ext_code' => '',
    'unsetgids' => '',
    'unsetroles' => '',
    'master_field' => '1',
    'ban_field' => '1',
    'location' => '0',
    'search_field' => '0',
    'ban_contribute' => '0',
    'to_fulltext' => '0',
    'to_block' => '0',
    'sort' => '30',
    'disabled' => '0',
    'powerful_field' => '0',
    'master_table' => 'insurance',
    'attr_table' => '',
  ),
)?>