<?php
 return array (
  1 => 
  array (
    'modelid' => '1',
    'm' => 'content',
    'name' => '文章模型',
    'master_table' => 'content_share',
    'attr_table' => 'news_data',
    'remark' => '',
    'template' => 'show',
    'css' => 'icon-file-word-o',
    'share_model' => '1',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  8 => 
  array (
    'modelid' => '8',
    'm' => 'content',
    'name' => '积分商城',
    'master_table' => 'point2goods',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1000 => 
  array (
    'modelid' => '1000',
    'm' => 'content',
    'name' => '装修公司',
    'master_table' => 'company',
    'attr_table' => 'company_data',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1001 => 
  array (
    'modelid' => '1001',
    'm' => 'content',
    'name' => '图库',
    'master_table' => 'picture',
    'attr_table' => 'picture_data',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1002 => 
  array (
    'modelid' => '1002',
    'm' => 'content',
    'name' => '发标',
    'master_table' => 'demand',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'demand_listing',
    'template_set' => '',
  ),
  1003 => 
  array (
    'modelid' => '1003',
    'm' => 'content',
    'name' => '设计团队',
    'master_table' => 'company_team',
    'attr_table' => 'company_team_data',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1004 => 
  array (
    'modelid' => '1004',
    'm' => 'content',
    'name' => '装修课堂',
    'master_table' => 'faq',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1005 => 
  array (
    'modelid' => '1005',
    'm' => 'content',
    'name' => '优惠活动',
    'master_table' => 'market_sale',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1006 => 
  array (
    'modelid' => '1006',
    'm' => 'content',
    'name' => '装修保险',
    'master_table' => 'insurance',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'insurance_listing',
    'template_set' => '',
  ),
  1007 => 
  array (
    'modelid' => '1007',
    'm' => 'content',
    'name' => '公司招聘',
    'master_table' => 'zhaopin',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1008 => 
  array (
    'modelid' => '1008',
    'm' => 'content',
    'name' => '团队介绍',
    'master_table' => 'tuandui',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1009 => 
  array (
    'modelid' => '1009',
    'm' => 'content',
    'name' => '品牌汇',
    'master_table' => 'brand',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1027 => 
  array (
    'modelid' => '1027',
    'm' => 'content',
    'name' => '装修日志',
    'master_table' => 'day_book',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1028 => 
  array (
    'modelid' => '1028',
    'm' => 'content',
    'name' => '装修案例',
    'master_table' => 'zxal',
    'attr_table' => 'zxal_data',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1029 => 
  array (
    'modelid' => '1029',
    'm' => 'content',
    'name' => '装修日志内容',
    'master_table' => 'day_log',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1031 => 
  array (
    'modelid' => '1031',
    'm' => 'content',
    'name' => '精品案例',
    'master_table' => 'm_picture',
    'attr_table' => 'm_picture_data',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1032 => 
  array (
    'modelid' => '1032',
    'm' => 'content',
    'name' => '公司',
    'master_table' => 'm_company',
    'attr_table' => 'm_company_data',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1033 => 
  array (
    'modelid' => '1033',
    'm' => 'content',
    'name' => '设计师',
    'master_table' => 'm_company_team',
    'attr_table' => 'm_company_team_data',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1034 => 
  array (
    'modelid' => '1034',
    'm' => 'content',
    'name' => '轮播图',
    'master_table' => 'm_carousel',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1035 => 
  array (
    'modelid' => '1035',
    'm' => 'content',
    'name' => '专题图',
    'master_table' => 'm_special',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1037 => 
  array (
    'modelid' => '1037',
    'm' => 'content',
    'name' => '专题列表',
    'master_table' => 'm_p_special',
    'attr_table' => 'm_p_special_data',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1038 => 
  array (
    'modelid' => '1038',
    'm' => 'content',
    'name' => '活动魔板',
    'master_table' => 'm_exercise',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1039 => 
  array (
    'modelid' => '1039',
    'm' => 'content',
    'name' => '财务设置付款方式',
    'master_table' => 'way_payment',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1040 => 
  array (
    'modelid' => '1040',
    'm' => 'content',
    'name' => '发布营销活动',
    'master_table' => 'activity',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
  1042 => 
  array (
    'modelid' => '1042',
    'm' => 'content',
    'name' => '推荐位-装修案例',
    'master_table' => 'tjw_picture',
    'attr_table' => '',
    'remark' => '',
    'template' => 'show',
    'css' => '',
    'share_model' => '0',
    'manage_template' => 'content_listing',
    'template_set' => '',
  ),
)?>